services:
  app1: &app1
    hostname: app1
    image: 'app1'
    build: .
    container_name: node_app1
    restart: always
    ports:
      - "7010:7001"
    volumes:
      - .:/app
      - /app/node_modules

  app2:
    <<: *app1
    image: 'app2'
    hostname: app2
    container_name: node_app2
    ports:
      - "7011:7001"

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      - app1
      - app2
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "10MB"
